spring:
  r2dbc:
    url: r2dbc:h2:mem:///employeedb
    username: admin
    password: admin
    pool:
      enabled: true
      initial-size: 5
      max-size: 10
logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
